$ErrorActionPreference = "Stop"
$BASE = "http://localhost:8080/api"
$XML  = @("-H", "Content-Type: application/xml", "-H", "Accept: application/xml")

function Section($t) { Write-Host "`n===== $t =====" -ForegroundColor Cyan }

function New-Survey($name, $desc) {
  $out = curl.exe -s -X POST "$BASE/surveys" @XML -d "<survey><name>$name</name><description>$desc</description></survey>"
  if ($out -match 'id="(\d+)"') { Write-Host "  Survey '$name' -> id $($Matches[1])"; return [int]$Matches[1] }
  throw "Survey create failed: $out"
}

function Add-Q($sid, $body) {
  $out = curl.exe -s -X POST "$BASE/surveys/$sid/questions" @XML -d $body
  if ($out -notmatch 'id="') { Write-Host "  QUESTION FAILED: $out" -ForegroundColor Red }
}

function Activate($sid)   { curl.exe -s -X PATCH "$BASE/surveys/$sid/activate"   -H "Accept: application/xml" | Out-Null }
function Deactivate($sid) { curl.exe -s -X PATCH "$BASE/surveys/$sid/deactivate" -H "Accept: application/xml" | Out-Null }
function Remove-Survey($sid) { curl.exe -s -X DELETE "$BASE/surveys/$sid" | Out-Null }

function Submit($sid, $fields) {
  $out = curl.exe -s -X POST "$BASE/surveys/$sid/responses" -H "Accept: application/xml" @fields
  if ($out -notmatch '<response ') { Write-Host "  SUBMIT FAILED: $out" -ForegroundColor Red }
}

function Q-Email() { "<question><name>email_address</name><prompt>What is your email address?</prompt><type>email</type><required>true</required></question>" }
function Q-Short($name, $prompt, $req) { "<question><name>$name</name><prompt>$prompt</prompt><type>short_text</type><required>$req</required><maxLength>150</maxLength></question>" }
function Q-Long($name, $prompt, $req) { "<question><name>$name</name><prompt>$prompt</prompt><type>long_text</type><required>$req</required><maxLength>500</maxLength></question>" }

$PDF = Join-Path $env:TEMP "seed-cert.pdf"
Set-Content -Path $PDF -Value "%PDF-1.4 dummy certificate generated by seed.ps1" -Encoding ascii

# ---------- S1: full five-type survey, 12 responses -> PAGINATION ----------
Section "S1 Graduate Developer Intake (pagination + all types)"
$s1 = New-Survey "Graduate Developer Intake" "Full-type survey with enough responses to paginate"
Add-Q $s1 (Q-Short "full_name" "What is your full name?" "true")
Add-Q $s1 (Q-Long  "motivation" "Why do you want this role?" "false")
Add-Q $s1 (Q-Email)
Add-Q $s1 "<question><name>programming_stack</name><prompt>Which stacks do you know?</prompt><type>choice</type><required>true</required><allowMultiple>true</allowMultiple><minSelection>1</minSelection><maxSelection>3</maxSelection><options><option><value>REACT</value><label>React JS</label></option><option><value>VUE</value><label>Vue JS</label></option><option><value>JAVA</value><label>Java</label></option><option><value>SPRING</value><label>Spring Boot</label></option></options></question>"
Add-Q $s1 "<question><name>experience_level</name><prompt>Your experience level?</prompt><type>choice</type><required>true</required><allowMultiple>false</allowMultiple><options><option><value>JUNIOR</value><label>Junior</label></option><option><value>MID</value><label>Mid-level</label></option><option><value>SENIOR</value><label>Senior</label></option></options></question>"
Add-Q $s1 "<question><name>certificates</name><prompt>Upload certificates</prompt><type>file</type><required>false</required><fileFormat>pdf</fileFormat><maxFileSize>5</maxFileSize><maxFileSizeUnit>mb</maxFileSizeUnit><allowMultipleFiles>true</allowMultipleFiles></question>"
Activate $s1

$stacks = @("REACT", "REACT,JAVA", "VUE,SPRING", "JAVA", "REACT,VUE,JAVA", "SPRING")
$levels = @("JUNIOR", "MID", "SENIOR")
for ($i = 1; $i -le 12; $i++) {
  $f = @("-F", "full_name=Candidate $i", "-F", "email_address=candidate$i@example.com",
        "-F", "programming_stack=$($stacks[$i % 6])", "-F", "experience_level=$($levels[$i % 3])")
  if ($i % 2 -eq 0) { $f += @("-F", "motivation=I enjoy building things, iteration $i.") }   # odd rows -> em-dash
  if ($i -le 3)     { $f += @("-F", "certificates=@$PDF;type=application/pdf") }             # first 3 -> download links
  Submit $s1 $f
}
Write-Host "  12 responses (pagination page 2 exists; odd rows blank motivation)"

# ---------- S2: shared email -> FILTER test ----------
Section "S2 Customer Feedback (email filter)"
$s2 = New-Survey "Customer Feedback" "Two responses share one email for filter testing"
Add-Q $s2 (Q-Email)
Add-Q $s2 "<question><name>rating</name><prompt>How satisfied are you?</prompt><type>choice</type><required>true</required><allowMultiple>false</allowMultiple><options><option><value>GOOD</value><label>Good</label></option><option><value>OKAY</value><label>Okay</label></option><option><value>POOR</value><label>Poor</label></option></options></question>"
Add-Q $s2 (Q-Long "comments" "Any comments?" "false")
Activate $s2
Submit $s2 @("-F", "email_address=jane@example.com", "-F", "rating=GOOD", "-F", "comments=Loved it.")
Submit $s2 @("-F", "email_address=jane@example.com", "-F", "rating=OKAY")
Submit $s2 @("-F", "email_address=omar@example.com", "-F", "rating=POOR", "-F", "comments=Too slow.")
Write-Host "  Filter by jane@example.com -> 2 rows; omar -> 1; nobody@nowhere.com -> empty"

# ---------- S3: simple registration ----------
Section "S3 Event Registration"
$s3 = New-Survey "Event Registration" "Simple single-choice survey"
Add-Q $s3 (Q-Short "full_name" "Your name?" "true")
Add-Q $s3 (Q-Email)
Add-Q $s3 "<question><name>tshirt_size</name><prompt>T-shirt size?</prompt><type>choice</type><required>true</required><allowMultiple>false</allowMultiple><options><option><value>S</value><label>Small</label></option><option><value>M</value><label>Medium</label></option><option><value>L</value><label>Large</label></option></options></question>"
Activate $s3
Submit $s3 @("-F", "full_name=Ada Lovelace", "-F", "email_address=ada@example.com", "-F", "tshirt_size=M")
Submit $s3 @("-F", "full_name=Alan Turing", "-F", "email_address=alan@example.com", "-F", "tshirt_size=L")

# ---------- S4: multi-choice with min/max ----------
Section "S4 Tech Stack Census"
$s4 = New-Survey "Tech Stack Census" "Multi-select with min 1 max 3"
Add-Q $s4 (Q-Email)
Add-Q $s4 "<question><name>languages</name><prompt>Languages you use weekly?</prompt><type>choice</type><required>true</required><allowMultiple>true</allowMultiple><minSelection>1</minSelection><maxSelection>3</maxSelection><options><option><value>JS</value><label>JavaScript</label></option><option><value>PY</value><label>Python</label></option><option><value>GO</value><label>Go</label></option><option><value>RS</value><label>Rust</label></option></options></question>"
Activate $s4
Submit $s4 @("-F", "email_address=dev1@example.com", "-F", "languages=JS,PY")
Submit $s4 @("-F", "email_address=dev2@example.com", "-F", "languages=GO")

# ---------- S5: required single file ----------
Section "S5 Document Upload Drill"
$s5 = New-Survey "Document Upload Drill" "Required single-file upload"
Add-Q $s5 (Q-Email)
Add-Q $s5 "<question><name>id_document</name><prompt>Upload your ID document</prompt><type>file</type><required>true</required><fileFormat>pdf</fileFormat><maxFileSize>2</maxFileSize><maxFileSizeUnit>mb</maxFileSizeUnit><allowMultipleFiles>false</allowMultipleFiles></question>"
Activate $s5
Submit $s5 @("-F", "email_address=uploader@example.com", "-F", "id_document=@$PDF;type=application/pdf")

# ---------- S6: special characters ----------
Section "S6 Q&A Session Signup (escaping round trip)"
$s6 = New-Survey "Q&amp;A Session Signup" "Name contains an ampersand &amp; tests escaping"
Add-Q $s6 (Q-Email)
Add-Q $s6 (Q-Short "topic" "Topic you want covered? (try symbols like &lt; and &amp;)" "true")
Activate $s6
Submit $s6 @("-F", "email_address=asker@example.com", "-F", "topic=Generics <T> and lambdas & streams")

# ---------- S7: INACTIVE after collecting a response ----------
Section "S7 Remote Work Pulse (deactivated with history)"
$s7 = New-Survey "Remote Work Pulse" "Activated, answered once, then deactivated"
Add-Q $s7 (Q-Email)
Add-Q $s7 "<question><name>work_mode</name><prompt>Preferred mode?</prompt><type>choice</type><required>true</required><allowMultiple>false</allowMultiple><options><option><value>REMOTE</value><label>Remote</label></option><option><value>HYBRID</value><label>Hybrid</label></option><option><value>OFFICE</value><label>Office</label></option></options></question>"
Activate $s7
Submit $s7 @("-F", "email_address=pulse@example.com", "-F", "work_mode=HYBRID")
Deactivate $s7
Write-Host "  INACTIVE badge in admin; hidden from respondents; response still viewable"

# ---------- S8: DRAFT, never activated ----------
Section "S8 Draft Ideas Board (stays DRAFT)"
$s8 = New-Survey "Draft Ideas Board" "Never activated - must NOT appear on respondent home"
Add-Q $s8 (Q-Email)
Add-Q $s8 (Q-Long "idea" "Describe your idea" "true")

# ---------- S9: soft-deleted with history ----------
Section "S9 Legacy Survey (soft-deleted)"
$s9 = New-Survey "Legacy Survey" "Answered once, then deleted - history preserved"
Add-Q $s9 (Q-Email)
Add-Q $s9 (Q-Short "legacy_field" "Legacy question" "true")
Activate $s9
Submit $s9 @("-F", "email_address=history@example.com", "-F", "legacy_field=Old data")
Remove-Survey $s9
Write-Host "  Struck-through 'deleted' badge, no action buttons, responses still reachable"

# ---------- S10: no email question -> the documented trap ----------
Section "S10 No Email Trap (submission always fails by design)"
$s10 = New-Survey "No Email Trap" "Activatable but unsubmittable - README known limitation"
Add-Q $s10 (Q-Short "just_text" "A question with no email sibling" "true")
Activate $s10
Write-Host "  Respond via UI -> banner: 'A valid email address answer is required'"

# ---------- S11: optional-heavy -> em-dash showcase ----------
Section "S11 Onboarding Checklist (em-dash showcase)"
$s11 = New-Survey "Onboarding Checklist" "Optional questions left blank render as em-dashes"
Add-Q $s11 (Q-Email)
Add-Q $s11 (Q-Short "nickname" "Preferred nickname?" "false")
Add-Q $s11 (Q-Long  "allergies" "Any allergies?" "false")
Add-Q $s11 (Q-Short "emergency_contact" "Emergency contact?" "false")
Activate $s11
Submit $s11 @("-F", "email_address=minimal@example.com")
Submit $s11 @("-F", "email_address=partial@example.com", "-F", "nickname=Kip")

Section "DONE - 11 surveys seeded"
Write-Host "Respondent home should show 8 surveys (S8 DRAFT, S7 INACTIVE, S9 deleted are hidden)."